### ISSUE TITLE
[Bug Report] showLoadingToast  报错

### ISSUE THREAD

**Issue by hexw** [vant-ui/vant#10854]
### 重现链接

showLoadingToast 

### Vant 版本

4.0.0-beta.0

### 描述一下你遇到的问题。

showLoadingToast 报错

vue-router.mjs?77c9:3420 Error: Cannot find module 'vant/es/show-loading-toast/style'
    at webpackMissingModule (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/order/evaluate.vue?vue&type=script&lang=js:4:50)
    at eval (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/order/evaluate.vue?vue&type=script&lang=js:4:157)
    at ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/pages/order/evaluate.vue?vue&type=script&lang=js (src_pages_order_evaluate_vue-node_modules_vant_es_dropdown-item_index_css-node_modules_vant_e-6b8a8a.js:18:1)
    at __webpack_require__ (app.js:219:33)
    at fn (app.js:484:21)
    at eval (evaluate.vue?vue&type=script&lang=js:5:211)
    at ./src/pages/order/evaluate.vue?vue&type=script&lang=js (src_pages_order_evaluate_vue-node_modules_vant_es_dropdown-item_index_css-node_modules_vant_e-6b8a8a.js:78:1)
    at __webpack_require__ (app.js:219:33)
    at fn (app.js:484:21)
    at eval (evaluate.vue:3:95)

### 重现步骤

showLoadingToast

**Comment by chenjiahan** [comment]
要把 babel-plugin-import 插件去掉哈，这个插件在 Vant 4 不再需要了

**Comment by hexw** [comment]
babel-plugin-import 插件去掉可以了,谢谢
